### ISSUE TITLE
number of reviewers is wrong

### ISSUE THREAD

**Issue by parkerth** [egouldo/ManyAnalysts#47]
https://github.com/egouldo/ManyAnalysts/blob/91ca56a15ab2630054e7391b9b90a2dc974feb65/index.qmd#L3741

Somehow, the number of reviewers in the rendered version is VERY wrong:
"We obtained reviews from 819 reviewers who reviewed analyses..."
It should be, I think, 128

**Comment by hannahsfraser** [comment]
I think I need to be able to generate the reviewers thing to work out how to fix this - and I cant on my computer at the moment. That number looks like the number of individual reviews though rather than reviewers.

**Comment by hannahsfraser** [comment]
I found some archived files that suggest that I did this properly at some point. Looking at Reconcile_Reviews.R in the ManyEcoEvo_identified repository. Do you remember whether this is what was drawn on to make the reviewers thing? It looks like maybe not but I might be being thick

**Comment by egouldo** [comment]
Thanks for looking into this @hannahsfraser , the number of reviewers and other summary statistics seemed to come from a chunk that was called `descriptive-data-mungeing-2` or similar, which was replicated in both the `index.qmd` doc as well as a second supplementary materials document. I recoded the code in that chunk because after adding the analysis with the reduced collinearity subset it no longer worked, as well as to reduce some memory overheads with the intermediate objects, then moved it into the ManyEcoEvo package ([here](https://github.com/egouldo/ManyEcoEvo/blob/a471343cbbd406a1286b3324ebf35dd6bd0d6f0a/R/calculate_descriptive_statistics.R#L175)) and executed it in the targets pipeline to make the object `ManyEcoEvo_study_summary` below (note that the reviewers calculations are still in `index.qmd`):

https://github.com/egouldo/ManyEcoEvo/blob/a471343cbbd406a1286b3324ebf35dd6bd0d6f0a/_targets.R#L233-L243

Here's the current code for calculating reviewers:

https://github.com/egouldo/ManyAnalysts/blame/420093ff9f064092a36e1fe561be65ad6542b786/index.qmd#L2477-L2515

Let's take a look at the git-blame for index.qmd to see how you had coded the reviewers last time:

https://github.com/egouldo/ManyAnalysts/blame/80151ecf564a5a3bdc896c10e8ba8df5530f4b0c/index.qmd#L2777-L2802

So this was not calculated manually in the most recent version. I'm also wondering if the current pipeline is correctly grouping out the collinearity analysis dataset from the other blue tit analyses, so that could also be a source of the issue.

**Comment by hannahsfraser** [comment]
My records show that 153 people submitted reviews - for now I'm just going to input that number. It might be tricky to get otherwise, because this includes reviews of things we discarded etc which might be why Tim thought there was a smaller number. For now I've done a manual fix. Let's come back to this if we have all the time in the world
See commit #56

**Comment by egouldo** [comment]
> My records show that 153 people submitted reviews - for now I'm just going to input that number. It might be tricky to get otherwise, because this includes reviews of things we discarded etc which might be why Tim thought there was a smaller number. For now I've done a manual fix. Let's come back to this if we have all the time in the world
> See commit #56

Thanks Hannah!
